In [1]:
import pandas as pd
import numpy as np
import scipy.stats as sps
data=pd.read_csv('final data.csv')

In [4]:
data=data.dropna()

In [5]:
#去掉非P
for i in data.index:
    if data.at[i,'Transtype'] != 'P':
        data.drop(i)

In [6]:
# add random column
data['Random'] = 0
for i in data.index:
    data.at[i,'Random'] = np.random.randint(100)

In [7]:
data.loc[1]

Date                               2010-03-08
Recnum                                  16628
Cardnum                            5142110081
Date.1                             2010-03-08
Merchnum                         930090121224
Merch description           X OFFICE DEPOT #1
Merch state                                WA
Merch zip                               98101
Transtype                                   P
Amount                                  495.9
Fraud                                       0
mean_Merchnum_0d                      121.698
Actual/mean_Merchnum_0d               4.07484
mean_Merchnum_1d                       37.002
Actual/mean_Merchnum_1d                13.402
mean_Merchnum_3d                      19.3796
Actual/mean_Merchnum_3d               25.5888
mean_Merchnum_7d                      96.3623
Actual/mean_Merchnum_7d                5.1462
mean_Merchnum_14d                     72.9589
Actual/mean_Merchnum_14d              6.79698
mean_Merchnum_30d                     124.175
Actual/mean_Merchnum_30d              3.99357
max_Merchnum_0d                         495.9
Actual/max_Merchnum_0d                      1
max_Merchnum_1d                           998
Actual/max_Merchnum_1d               0.496894
max_Merchnum_3d                           998
Actual/max_Merchnum_3d               0.496894
max_Merchnum_7d                       3657.54
                                  ...
Actual/sum_Cardnum_7d                       1
sum_Cardnum_14d                         495.9
Actual/sum_Cardnum_14d                      1
sum_Cardnum_30d                         495.9
Actual/sum_Cardnum_30d                      1
count_Cardnum_0d                            1
Actual/count_Cardnum_0d                 495.9
count_Cardnum_1d                            1
Actual/count_Cardnum_1d                 495.9
count_Cardnum_3d                            1
Actual/count_Cardnum_3d                 495.9
count_Cardnum_7d                            1
Actual/count_Cardnum_7d                 495.9
count_Cardnum_14d                           1
Actual/count_Cardnum_14d                495.9
count_Cardnum_30d                           1
Actual/count_Cardnum_30d                495.9
AMTCardnum0/7Vel                            7
AMTMerchnum0/7Vel                    0.122784
AMTCardnum0/14Vel                          14
AMTMerchnum0/14Vel                   0.188327
AMTCardnum0/30Vel                          30
AMTMerchnum0/30Vel                   0.205606
AMTCardnum1/7Vel                            7
AMTMerchnum1/7Vel                    0.567449
AMTCardnum1/14Vel                          14
AMTMerchnum1/14Vel                   0.870356
AMTCardnum1/30Vel                          30
AMTMerchnum1/30Vel                   0.950212
Random                                     92
Name: 1, Length: 359, dtype: object

In [9]:
# 分隔OTT，以后的内容用data_test
a=0
for i in data.index:
    if str(data.at[i,'Date']) == '2010-11-01 00:00:00':
        a = i
        break

data_test = pd.DataFrame(columns=data.columns)
k=0
for i in data.index:
    if i < a:
        k+=1
k
data_test = data.head(k)

In [10]:
nvars = len(data.columns)
nvars

359

In [11]:
goods = data[data['Fraud']==0]
bads = data[data['Fraud']==1]
numgoods = len(goods)
numbads = len(bads)

In [12]:
KS = pd.DataFrame(np.zeros((nvars,3)))
i = 0
for col in data:
    KS.loc[i,0] = col
    i+=1
KS

                            0    1    2
0                        Date  0.0  0.0
1                      Recnum  0.0  0.0
2                     Cardnum  0.0  0.0
3                      Date.1  0.0  0.0
4                    Merchnum  0.0  0.0
5           Merch description  0.0  0.0
6                 Merch state  0.0  0.0
7                   Merch zip  0.0  0.0
8                   Transtype  0.0  0.0
9                      Amount  0.0  0.0
10                      Fraud  0.0  0.0
11           mean_Merchnum_0d  0.0  0.0
12    Actual/mean_Merchnum_0d  0.0  0.0
13           mean_Merchnum_1d  0.0  0.0
14    Actual/mean_Merchnum_1d  0.0  0.0
15           mean_Merchnum_3d  0.0  0.0
16    Actual/mean_Merchnum_3d  0.0  0.0
17           mean_Merchnum_7d  0.0  0.0
18    Actual/mean_Merchnum_7d  0.0  0.0
19          mean_Merchnum_14d  0.0  0.0
20   Actual/mean_Merchnum_14d  0.0  0.0
21          mean_Merchnum_30d  0.0  0.0
22   Actual/mean_Merchnum_30d  0.0  0.0
23            max_Merchnum_0d  0.0  0.0
24     Actual/max_Merchnum_0d  0.0  0.0
25            max_Merchnum_1d  0.0  0.0
26     Actual/max_Merchnum_1d  0.0  0.0
27            max_Merchnum_3d  0.0  0.0
28     Actual/max_Merchnum_3d  0.0  0.0
29            max_Merchnum_7d  0.0  0.0
..                        ...  ...  ...
329     Actual/sum_Cardnum_7d  0.0  0.0
330           sum_Cardnum_14d  0.0  0.0
331    Actual/sum_Cardnum_14d  0.0  0.0
332           sum_Cardnum_30d  0.0  0.0
333    Actual/sum_Cardnum_30d  0.0  0.0
334          count_Cardnum_0d  0.0  0.0
335   Actual/count_Cardnum_0d  0.0  0.0
336          count_Cardnum_1d  0.0  0.0
337   Actual/count_Cardnum_1d  0.0  0.0
338          count_Cardnum_3d  0.0  0.0
339   Actual/count_Cardnum_3d  0.0  0.0
340          count_Cardnum_7d  0.0  0.0
341   Actual/count_Cardnum_7d  0.0  0.0
342         count_Cardnum_14d  0.0  0.0
343  Actual/count_Cardnum_14d  0.0  0.0
344         count_Cardnum_30d  0.0  0.0
345  Actual/count_Cardnum_30d  0.0  0.0
346          AMTCardnum0/7Vel  0.0  0.0
347         AMTMerchnum0/7Vel  0.0  0.0
348         AMTCardnum0/14Vel  0.0  0.0
349        AMTMerchnum0/14Vel  0.0  0.0
350         AMTCardnum0/30Vel  0.0  0.0
351        AMTMerchnum0/30Vel  0.0  0.0
352          AMTCardnum1/7Vel  0.0  0.0
353         AMTMerchnum1/7Vel  0.0  0.0
354         AMTCardnum1/14Vel  0.0  0.0
355        AMTMerchnum1/14Vel  0.0  0.0
356         AMTCardnum1/30Vel  0.0  0.0
357        AMTMerchnum1/30Vel  0.0  0.0
358                    Random  0.0  0.0

[359 rows x 3 columns]

In [13]:
KS.columns = ['field','KS','FDR']
KS

                        field   KS  FDR
0                        Date  0.0  0.0
1                      Recnum  0.0  0.0
2                     Cardnum  0.0  0.0
3                      Date.1  0.0  0.0
4                    Merchnum  0.0  0.0
5           Merch description  0.0  0.0
6                 Merch state  0.0  0.0
7                   Merch zip  0.0  0.0
8                   Transtype  0.0  0.0
9                      Amount  0.0  0.0
10                      Fraud  0.0  0.0
11           mean_Merchnum_0d  0.0  0.0
12    Actual/mean_Merchnum_0d  0.0  0.0
13           mean_Merchnum_1d  0.0  0.0
14    Actual/mean_Merchnum_1d  0.0  0.0
15           mean_Merchnum_3d  0.0  0.0
16    Actual/mean_Merchnum_3d  0.0  0.0
17           mean_Merchnum_7d  0.0  0.0
18    Actual/mean_Merchnum_7d  0.0  0.0
19          mean_Merchnum_14d  0.0  0.0
20   Actual/mean_Merchnum_14d  0.0  0.0
21          mean_Merchnum_30d  0.0  0.0
22   Actual/mean_Merchnum_30d  0.0  0.0
23            max_Merchnum_0d  0.0  0.0
24     Actual/max_Merchnum_0d  0.0  0.0
25            max_Merchnum_1d  0.0  0.0
26     Actual/max_Merchnum_1d  0.0  0.0
27            max_Merchnum_3d  0.0  0.0
28     Actual/max_Merchnum_3d  0.0  0.0
29            max_Merchnum_7d  0.0  0.0
..                        ...  ...  ...
329     Actual/sum_Cardnum_7d  0.0  0.0
330           sum_Cardnum_14d  0.0  0.0
331    Actual/sum_Cardnum_14d  0.0  0.0
332           sum_Cardnum_30d  0.0  0.0
333    Actual/sum_Cardnum_30d  0.0  0.0
334          count_Cardnum_0d  0.0  0.0
335   Actual/count_Cardnum_0d  0.0  0.0
336          count_Cardnum_1d  0.0  0.0
337   Actual/count_Cardnum_1d  0.0  0.0
338          count_Cardnum_3d  0.0  0.0
339   Actual/count_Cardnum_3d  0.0  0.0
340          count_Cardnum_7d  0.0  0.0
341   Actual/count_Cardnum_7d  0.0  0.0
342         count_Cardnum_14d  0.0  0.0
343  Actual/count_Cardnum_14d  0.0  0.0
344         count_Cardnum_30d  0.0  0.0
345  Actual/count_Cardnum_30d  0.0  0.0
346          AMTCardnum0/7Vel  0.0  0.0
347         AMTMerchnum0/7Vel  0.0  0.0
348         AMTCardnum0/14Vel  0.0  0.0
349        AMTMerchnum0/14Vel  0.0  0.0
350         AMTCardnum0/30Vel  0.0  0.0
351        AMTMerchnum0/30Vel  0.0  0.0
352          AMTCardnum1/7Vel  0.0  0.0
353         AMTMerchnum1/7Vel  0.0  0.0
354         AMTCardnum1/14Vel  0.0  0.0
355        AMTMerchnum1/14Vel  0.0  0.0
356         AMTCardnum1/30Vel  0.0  0.0
357        AMTMerchnum1/30Vel  0.0  0.0
358                    Random  0.0  0.0

[359 rows x 3 columns]

In [14]:
%%time
i = 0
for col in data:
    KS['KS'][i] = sps.ks_2samp(goods[col],bads[col])[0]
    i+=1

/Users/yucenzhao/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

CPU times: user 15.1 s, sys: 193 ms, total: 15.3 s
Wall time: 15.5 s

In [15]:
%%time
topRows = int(round(len(data)*0.03))
j = 0
for col in data:
    temp1 = data.sort_values(col,ascending=False).head(topRows)
    temp2 = data.sort_values(col,ascending=True).head(topRows)
    needed1 = temp1.loc[:,'Fraud']
    needed2 = temp2.loc[:,'Fraud']
    FDR1 = sum(needed1)/numbads
    FDR2 = sum(needed2)/numbads
    FDRate = np.maximum(FDR1,FDR2)
    KS.loc[j,'FDR'] = FDRate
    j = j+1

CPU times: user 2min 25s, sys: 1min 30s, total: 3min 56s
Wall time: 4min 4s

In [16]:
KS

                        field        KS       FDR
0                        Date  0.199175  0.049103
1                      Recnum  0.199415  0.050047
2                     Cardnum  0.126534  0.070822
3                      Date.1  0.199175  0.049103
4                    Merchnum  0.081505  0.051936
5           Merch description  0.070513  0.051936
6                 Merch state  0.211730  0.081209
7                   Merch zip  0.178062  0.128423
8                   Transtype  0.003699  0.018886
9                      Amount  0.479659  0.277620
10                      Fraud  1.000000  1.000000
11           mean_Merchnum_0d  0.511220  0.269122
12    Actual/mean_Merchnum_0d  0.151667  0.061379
13           mean_Merchnum_1d  0.508530  0.257790
14    Actual/mean_Merchnum_1d  0.201071  0.067044
15           mean_Merchnum_3d  0.489064  0.239849
16    Actual/mean_Merchnum_3d  0.240678  0.094429
17           mean_Merchnum_7d  0.496275  0.260623
18    Actual/mean_Merchnum_7d  0.280103  0.108593
19          mean_Merchnum_14d  0.466259  0.254958
20   Actual/mean_Merchnum_14d  0.275136  0.132200
21          mean_Merchnum_30d  0.443824  0.189802
22   Actual/mean_Merchnum_30d  0.311903  0.162417
23            max_Merchnum_0d  0.512200  0.361662
24     Actual/max_Merchnum_0d  0.110210  0.040604
25            max_Merchnum_1d  0.487167  0.386213
26     Actual/max_Merchnum_1d  0.137608  0.040604
27            max_Merchnum_3d  0.458668  0.277620
28     Actual/max_Merchnum_3d  0.121617  0.051936
29            max_Merchnum_7d  0.418119  0.247403
..                        ...       ...       ...
329     Actual/sum_Cardnum_7d  0.204907  0.015109
330           sum_Cardnum_14d  0.527552  0.437205
331    Actual/sum_Cardnum_14d  0.131216  0.024551
332           sum_Cardnum_30d  0.463177  0.366383
333    Actual/sum_Cardnum_30d  0.142790  0.017941
334          count_Cardnum_0d  0.322852  0.160529
335   Actual/count_Cardnum_0d  0.292307  0.118980
336          count_Cardnum_1d  0.378093  0.247403
337   Actual/count_Cardnum_1d  0.232663  0.083097
338          count_Cardnum_3d  0.432069  0.180359
339   Actual/count_Cardnum_3d  0.218944  0.074599
340          count_Cardnum_7d  0.426477  0.080264
341   Actual/count_Cardnum_7d  0.228277  0.075543
342         count_Cardnum_14d  0.358759  0.024551
343  Actual/count_Cardnum_14d  0.254458  0.075543
344         count_Cardnum_30d  0.282027  0.017941
345  Actual/count_Cardnum_30d  0.295921  0.081209
346          AMTCardnum0/7Vel  0.073175  0.012276
347         AMTMerchnum0/7Vel  0.150177  0.038716
348         AMTCardnum0/14Vel  0.158918  0.018886
349        AMTMerchnum0/14Vel  0.148229  0.040604
350         AMTCardnum0/30Vel  0.255558  0.019830
351        AMTMerchnum0/30Vel  0.191385  0.024551
352          AMTCardnum1/7Vel  0.174315  0.007554
353         AMTMerchnum1/7Vel  0.160906  0.043437
354         AMTCardnum1/14Vel  0.290372  0.021719
355        AMTMerchnum1/14Vel  0.227532  0.041549
356         AMTCardnum1/30Vel  0.357791  0.032106
357        AMTMerchnum1/30Vel  0.251247  0.040604
358                    Random  0.015755  0.039660

[359 rows x 3 columns]

In [17]:
S = pd.DataFrame(np.zeros((3,3)))
S.columns = ['field','KS','FDR']
S['K'] = [1,2,3]
S

   field   KS  FDR  K
0    0.0  0.0  0.0  1
1    0.0  0.0  0.0  2
2    0.0  0.0  0.0  3

In [34]:
KS.sort_values(by=['KS'],ascending=False, inplace=True)

In [35]:
by_KS=KS

In [25]:
by_KS

                                   field        KS       FDR
10                                 Fraud  1.000000  1.000000
173             sum_Cardnum_Merch zip_7d  0.663331  0.593957
175            sum_Cardnum_Merch zip_14d  0.649672  0.604344
171             sum_Cardnum_Merch zip_3d  0.647758  0.577904
233           sum_Cardnum_Merch state_7d  0.647575  0.537299
231           sum_Cardnum_Merch state_3d  0.639630  0.559018
113              sum_Cardnum_Merchnum_7d  0.637604  0.583569
177            sum_Cardnum_Merch zip_30d  0.634791  0.532578
235          sum_Cardnum_Merch state_14d  0.631601  0.498584
115             sum_Cardnum_Merchnum_14d  0.629422  0.590179
111              sum_Cardnum_Merchnum_3d  0.627136  0.558074
151            max_Cardnum_Merch zip_14d  0.623272  0.446648
149             max_Cardnum_Merch zip_7d  0.619978  0.429651
153            max_Cardnum_Merch zip_30d  0.619968  0.452314
117             sum_Cardnum_Merchnum_30d  0.614649  0.530689
169             sum_Cardnum_Merch zip_1d  0.606038  0.527856
229           sum_Cardnum_Merch state_1d  0.605309  0.529745
91              max_Cardnum_Merchnum_14d  0.604259  0.428706
93              max_Cardnum_Merchnum_30d  0.603051  0.426818
89               max_Cardnum_Merchnum_7d  0.602450  0.421152
209           max_Cardnum_Merch state_7d  0.602127  0.451369
237          sum_Cardnum_Merch state_30d  0.597871  0.413598
211          max_Cardnum_Merch state_14d  0.595286  0.458924
147             max_Cardnum_Merch zip_3d  0.593218  0.435316
109              sum_Cardnum_Merchnum_1d  0.592978  0.527856
207           max_Cardnum_Merch state_3d  0.588476  0.431539
87               max_Cardnum_Merchnum_3d  0.577774  0.427762
205           max_Cardnum_Merch state_1d  0.571701  0.397545
145             max_Cardnum_Merch zip_1d  0.571090  0.411709
213          max_Cardnum_Merch state_30d  0.566673  0.450425
..                                   ...       ...       ...
353                    AMTMerchnum1/7Vel  0.160906  0.043437
72       Actual/mean_Cardnum_Merchnum_0d  0.159448  0.101039
348                    AMTCardnum0/14Vel  0.158918  0.018886
166  Actual/median_Cardnum_Merch zip_30d  0.158423  0.065156
106   Actual/median_Cardnum_Merchnum_30d  0.158162  0.078376
156   Actual/median_Cardnum_Merch zip_0d  0.153459  0.094429
82      Actual/mean_Cardnum_Merchnum_30d  0.152960  0.070822
12               Actual/mean_Merchnum_0d  0.151667  0.061379
347                    AMTMerchnum0/7Vel  0.150177  0.038716
142    Actual/mean_Cardnum_Merch zip_30d  0.148816  0.064212
349                   AMTMerchnum0/14Vel  0.148229  0.040604
96     Actual/median_Cardnum_Merchnum_0d  0.147116  0.092540
333               Actual/sum_Cardnum_30d  0.142790  0.017941
56               Actual/sum_Merchnum_14d  0.141562  0.037771
32               Actual/max_Merchnum_14d  0.141185  0.037771
26                Actual/max_Merchnum_1d  0.137608  0.040604
214   Actual/max_Cardnum_Merch state_30d  0.137491  0.030217
36             Actual/median_Merchnum_0d  0.136989  0.044381
305                Actual/max_Cardnum_7d  0.132645  0.030217
331               Actual/sum_Cardnum_14d  0.131216  0.024551
58               Actual/sum_Merchnum_30d  0.129108  0.037771
2                                Cardnum  0.126534  0.070822
28                Actual/max_Merchnum_3d  0.121617  0.051936
30                Actual/max_Merchnum_7d  0.111929  0.050992
24                Actual/max_Merchnum_0d  0.110210  0.040604
4                               Merchnum  0.081505  0.051936
346                     AMTCardnum0/7Vel  0.073175  0.012276
5                      Merch description  0.070513  0.051936
358                               Random  0.015755  0.039660
8                              Transtype  0.003699  0.018886

[359 rows x 3 columns]

In [29]:
KS.sort_values(by=['FDR'],ascending=False, inplace=True)

In [30]:
by_FDR=KS

In [31]:
by_FDR

                           field        KS       FDR
10                         Fraud  1.000000  1.000000
175    sum_Cardnum_Merch zip_14d  0.649672  0.604344
173     sum_Cardnum_Merch zip_7d  0.663331  0.593957
115     sum_Cardnum_Merchnum_14d  0.629422  0.590179
113      sum_Cardnum_Merchnum_7d  0.637604  0.583569
171     sum_Cardnum_Merch zip_3d  0.647758  0.577904
231   sum_Cardnum_Merch state_3d  0.639630  0.559018
111      sum_Cardnum_Merchnum_3d  0.627136  0.558074
233   sum_Cardnum_Merch state_7d  0.647575  0.537299
177    sum_Cardnum_Merch zip_30d  0.634791  0.532578
117     sum_Cardnum_Merchnum_30d  0.614649  0.530689
326               sum_Cardnum_3d  0.563248  0.530689
229   sum_Cardnum_Merch state_1d  0.605309  0.529745
109      sum_Cardnum_Merchnum_1d  0.592978  0.527856
169     sum_Cardnum_Merch zip_1d  0.606038  0.527856
306              max_Cardnum_14d  0.485555  0.500472
324               sum_Cardnum_1d  0.533933  0.499528
235  sum_Cardnum_Merch state_14d  0.631601  0.498584
107      sum_Cardnum_Merchnum_0d  0.544052  0.495751
322               sum_Cardnum_0d  0.512502  0.491974
227   sum_Cardnum_Merch state_0d  0.548773  0.491974
167     sum_Cardnum_Merch zip_0d  0.550499  0.491974
328               sum_Cardnum_7d  0.555672  0.490085
304               max_Cardnum_7d  0.511341  0.468366
211  max_Cardnum_Merch state_14d  0.595286  0.458924
153    max_Cardnum_Merch zip_30d  0.619968  0.452314
209   max_Cardnum_Merch state_7d  0.602127  0.451369
213  max_Cardnum_Merch state_30d  0.566673  0.450425
151    max_Cardnum_Merch zip_14d  0.623272  0.446648
330              sum_Cardnum_14d  0.527552  0.437205
..                           ...       ...       ...
350            AMTCardnum0/30Vel  0.255558  0.019830
348            AMTCardnum0/14Vel  0.158918  0.018886
8                      Transtype  0.003699  0.018886
327        Actual/sum_Cardnum_3d  0.282595  0.018886
65             count_Merchnum_7d  0.232784  0.018886
333       Actual/sum_Cardnum_30d  0.142790  0.017941
344            count_Cardnum_30d  0.282027  0.017941
48        Actual/sum_Merchnum_0d  0.177309  0.017941
329        Actual/sum_Cardnum_7d  0.204907  0.015109
67            count_Merchnum_14d  0.233242  0.015109
69            count_Merchnum_30d  0.191929  0.014164
282                  Merch_Fre30  0.379000  0.013220
262                   Merch_Fre1  0.350831  0.013220
284               Card/Zip_Fre30  0.379000  0.013220
265              Card/State_Fre1  0.350831  0.013220
263              Card/Merch_Fre1  0.350831  0.013220
283             Card/Merch_Fre30  0.379000  0.013220
261                    Card_Fre1  0.350831  0.013220
264                Card/Zip_Fre1  0.350831  0.013220
281                   Card_Fre30  0.379000  0.013220
285             Card/State_Fre30  0.379000  0.013220
346             AMTCardnum0/7Vel  0.073175  0.012276
52        Actual/sum_Merchnum_3d  0.202331  0.009443
61             count_Merchnum_1d  0.234465  0.008499
352             AMTCardnum1/7Vel  0.174315  0.007554
266                    Card_Fre3  0.346942  0.006610
267                   Merch_Fre3  0.346942  0.006610
269                Card/Zip_Fre3  0.346942  0.006610
268              Card/Merch_Fre3  0.346942  0.006610
270              Card/State_Fre3  0.346942  0.006610

[359 rows x 3 columns]

In [32]:
by_FDR.to_csv('Project2_sortby_FDR.csv')

In [36]:
by_KS.to_csv('Project2_sortby_KS.csv')